[package]
name = "make-gitignore"
version = "0.1.0"
edition = "2024"
authors=["Alex Younger <thealexyounger@proton.me>"]
description="TUI for creating gitignore files - fetched from Github official gitignore repo."
license="MIT"
publish=true


[[bin]]
name = "gitignore"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0"
ratatui = { version = "0.30.0", features = ["crossterm"] }
reqwest = { version = "0.13.1", features = ["blocking"] }
tokio = "1.49.0"
zip = "7.0.0"
